name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1
          6.0
    - name: Build and Test
      env:
        DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
        TERM: xterm
      run: pwsh ./build.ps1